In [63]:
import random
import pandas as pd

one = []
two = []
three = []
four = []

for j in range(1, 17):
  one.append(j)
  two.append(j)
  three.append(j)
  four.append(j)

random.shuffle(one)
random.shuffle(two)
random.shuffle(three)
random.shuffle(four)

# for i in one:
#   if(i == 7):
#     one.remove(i)
#     one.insert(i, 0)

# for i in four:
#   if((i == 8) | (i == 9)):
#     four.remove(i)
#     four.insert(i, 0)

df = pd.DataFrame([list(range(1,17)),one,two,three,four])
df = df.T
df.columns = ['조', '1반', '2반', '3반', '4반']
df = df.set_index('조')
df.loc[df[df['1반'] == 16].index, '1반'] = '없음'
df.loc[df[df['2반'] == 8].index, '2반'] = '(8)안올수도있음'
df.loc[df[df['4반'] == 8].index, '4반'] = '없음'
df.loc[df[df['4반'] == 9].index, '4반'] = '없음'

df

    1반         2반  3반  4반
조
1   14         15  13   4
2    5          3  10  13
3   13          9   7   6
4   15         11   8  10
5    7         16  11   5
6    2         14   2   7
7    9          2  15   2
8    4         13  12  12
9    8          1   3  11
10   1          6  14   1
11   6  (8)안올수도있음  16  15
12  없음          7   4  없음
13  12          5   5  14
14   3         10   9  16
15  11         12   6   3
16  10          4   1  없음

In [ ]:
import random
import pandas as pd

ban = []
for i in range(1, 17):
  ban.append(i)